# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2022-11-23 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='title',
            field=models.CharField(default='test', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term100key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term100value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term10key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term10value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term11key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term11value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term12key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term12value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term13key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term13value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term14key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term14value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term15key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term15value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term16key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term16value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term17key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term17value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term18key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term18value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term19key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term19value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term20key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term20value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term21key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term21value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term22key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term22value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term23key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term23value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term24key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term24value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term25key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term25value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term26key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term26value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term27key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term27value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term28key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term28value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term29key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term29value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term30key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term30value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term31key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term31value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term32key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term32value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term33key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term33value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term34key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term34value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term35key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term35value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term36key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term36value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term37key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term37value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term38key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term38value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term39key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term39value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term40key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term40value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term41key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term41value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term42key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term42value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term43key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term43value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term44key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term44value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term45key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term45value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term46key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term46value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term47key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term47value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term48key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term48value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term49key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term49value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term4key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term4value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term50key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term50value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term51key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term51value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term52key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term52value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term53key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term53value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term54key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term54value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term55key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term55value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term56key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term56value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term57key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term57value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term58key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term58value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term59key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term59value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term5key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term5value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term60key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term60value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term61key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term61value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term62key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term62value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term63key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term63value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term64key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term64value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term65key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term65value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term66key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term66value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term67key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term67value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term68key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term68value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term69key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term69value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term6key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term6value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term70key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term70value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term71key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term71value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term72key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term72value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term73key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term73value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term74key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term74value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term75key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term75value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term76key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term76value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term77key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term77value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term78key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term78value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term79key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term79value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term7key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term7value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term80key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term80value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term81key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term81value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term82key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term82value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term83key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term83value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term84key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term84value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term85key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term85value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term86key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term86value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term87key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term87value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term88key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term88value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term89key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term89value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term8key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term8value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term90key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term90value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term91key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term91value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term92key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term92value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term93key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term93value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term94key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term94value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term95key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term95value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term96key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term96value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term97key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term97value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term98key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term98value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term99key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term99value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term9key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='term9value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
